# Generated by Django 3.1.3 on 2020-11-10 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_elements', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('description', models.TextField()),
                ('thickness', models.IntegerField(null=True)),
                ('minimal_draft_angle', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.client')),
                ('fixing_element', models.ManyToManyField(related_name='fixing_project_view', through='project_view.Fix', to='project_view.Fixing')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.module')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Topical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_description', models.TextField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.part')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.topic')),
            ],
            options={
                'unique_together': {('part', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.project'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.supplier'),
        ),
        migrations.AddField(
            model_name='part',
            name='topic',
            field=models.ManyToManyField(related_name='topic_project_view', through='project_view.Topical', to='project_view.Topic'),
        ),
        migrations.AddField(
            model_name='fix',
            name='fixing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.fixing'),
        ),
        migrations.AddField(
            model_name='fix',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.part'),
        ),
        migrations.AlterUniqueTogether(
            name='fix',
            unique_together={('part', 'fixing')},
        ),
    ]
