# Generated by Django 3.1.3 on 2020-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topical',
            name='topic_description',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
