# Generated by Django 3.1.3 on 2020-11-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0002_auto_20201111_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='topic',
        ),
        migrations.AddField(
            model_name='part',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_view.topic'),
        ),
        migrations.DeleteModel(
            name='Topical',
        ),
    ]
