# Generated by Django 3.1.3 on 2020-11-18 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0003_auto_20201111_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='client',
        ),
        migrations.RemoveField(
            model_name='part',
            name='project',
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_view.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_view.client'),
        ),
    ]
