# Generated by Django 3.1.3 on 2020-11-23 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0005_auto_20201118_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')]),
        ),
    ]
