# Generated by Django 3.1.3 on 2020-11-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0011_auto_20201130_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_view.part'),
        ),
    ]
