# Generated by Django 3.1.3 on 2020-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0012_auto_20201130_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
