# Generated by Django 3.1.3 on 2020-12-09 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0016_picture_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('problem_description', models.TextField()),
                ('problem_solution', models.TextField()),
                ('agreed_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreed_with_participants', to='project_view.participant')),
                ('involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_participants', to='project_view.participant')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_participants', to='project_view.participant')),
            ],
        ),
    ]
