# Generated by Django 3.1.3 on 2020-12-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0017_entries_participant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Entry',
        ),
    ]
