# Generated by Django 3.1.3 on 2020-12-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0018_auto_20201209_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_view.project'),
        ),
    ]
