# Generated by Django 3.1.3 on 2020-12-09 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_view', '0020_participant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='project',
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='participant',
            field=models.ManyToManyField(related_name='participation_project_view', through='project_view.Participation', to='project_view.Participant'),
        ),
    ]
