# Generated by Django 3.1.3 on 2020-12-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0022_entry_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
