# Generated by Django 3.1.3 on 2020-12-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0023_remove_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
