# Generated by Django 3.1.3 on 2020-12-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0024_topic_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='problem_solution',
            new_name='solution',
        ),
    ]
