# Generated by Django 3.1.3 on 2020-12-15 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0025_auto_20201214_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
