# Generated by Django 3.1.3 on 2020-12-16 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_view', '0027_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='responsible',
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.entry')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.participant')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='responsible',
            field=models.ManyToManyField(related_name='responsible_participants', through='project_view.Responsibility', to='project_view.Participant'),
        ),
    ]
