# Generated by Django 3.1.3 on 2020-12-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0028_auto_20201216_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='owner',
        ),
    ]
