# Generated by Django 3.1.3 on 2020-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0029_remove_responsibility_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='agreed_with',
        ),
        migrations.AddField(
            model_name='entry',
            name='agreed_with',
            field=models.ManyToManyField(related_name='agreed_with_participants', to='project_view.Participant'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='involved',
        ),
        migrations.AddField(
            model_name='entry',
            name='involved',
            field=models.ManyToManyField(related_name='involved_participants', to='project_view.Participant'),
        ),
    ]
