# Generated by Django 3.1.3 on 2020-12-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0030_auto_20201217_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='minimal_draft_angle',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='thickness',
            field=models.FloatField(null=True),
        ),
    ]
