# Generated by Django 3.1.3 on 2020-12-30 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0031_auto_20201228_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_view.status'),
        ),
    ]
