# Generated by Django 3.1.3 on 2020-12-31 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0032_auto_20201230_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
