# Generated by Django 3.1.3 on 2021-01-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_view', '0033_auto_20201231_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('part', 'user')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='my_parts',
            field=models.ManyToManyField(related_name='my_parts_project_view', through='project_view.My_part', to=settings.AUTH_USER_MODEL),
        ),
    ]
