# Generated by Django 3.1.3 on 2021-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0035_auto_20210114_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('project', 'participant')},
        ),
    ]
