# Generated by Django 3.1.3 on 2021-01-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0036_auto_20210129_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
    ]
