# Generated by Django 3.1.3 on 2021-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0039_auto_20210205_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participant',
        ),
        migrations.AddField(
            model_name='participant',
            name='project',
            field=models.ManyToManyField(related_name='participation_project_view', through='project_view.Participation', to='project_view.Project'),
        ),
    ]
