# Generated by Django 3.1.3 on 2021-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0042_auto_20210208_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
