# Generated by Django 3.1.3 on 2021-02-12 19:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_view', '0043_auto_20210208_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_user', to=settings.AUTH_USER_MODEL)),
                ('check_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_view.check_box')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_view.status')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
