# Generated by Django 3.1.3 on 2021-02-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0044_check_box_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='check_box',
        ),
    ]
