# Generated by Django 3.1.3 on 2021-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_view', '0045_remove_todo_check_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
